server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/auth
    username: postgres
    password: mysecretpassword
  flyway:
    enabled: true
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
